[workspace]
name = "fastquorum-pixi"
description = "Fastquorum pipeline using Pixi"
version = "1.0.0"
authors = ["Vaibhav Upreti"]
channels = ["conda-forge", "bioconda"]
platforms = ["osx-arm64", "osx-64", "linux-64", "linux-aarch64"]

[dependencies]
nextflow = ">=24.10.0"
# conda = ">=24.0.0"

fastqc = ">=0.12.1"
samtools = ">=1.22"
fgbio = ">=2.0.0"
bwa = ">=0.7.17"
multiqc = ">=1.17"

# bcftools = ">=1.22"
# gatk4 = ">=4.4.0.0"

[tasks]
# pipeline = "nextflow run nf-core/fastquorum -c ../../shared/fastquorum/custom.config -profile test --input ../../shared/fastquorum/samplesheet.csv --outdir results"
pipeline= "nextflow run nf-core/fastquorum -c ../../shared/fastquorum/custom.config -profile test --input ../../shared/fastquorum/samplesheet.csv --outdir results --fasta ../../shared/fastquorum/references/chr17.fa"
pipeline_full = "nextflow run nf-core/fastquorum -c ../../shared/fastquorum/custom.config -profile test_full --outdir results"
pipeline-custom = "nextflow run nf-core/fastquorum -c ../../shared/fastquorum/custom.config -profile test --input $1 --outdir $2 --genome $3"

test = "nextflow run nf-core/fastquorum -c ../../shared/fastquorum/custom.config -profile test --input samplesheet.csv --outdir test_results"

clean = { cmd = [
    "/bin/sh",
    "-c",
    "rm -rf results logs work test_results custom_results .nextflow*"
]}

[feature.dev.dependencies]
nextflow = ">=24.10.0"

[environments]
default = ["dev"]
