pipelines/
└── linux-arm-ubuntu/
    └── pixi.toml
    ├── environment.yml
    ├── main.nf
    ├── nextflow.config
    ├── run.sh
    └── test_data/
        ├── sample1.fasta
        └── sample2.fasta
