[project]
name = "nextflow-minimal"
channels = ["conda-forge", "bioconda", "defaults"]
platforms = ["linux-aarch64"]

[dependencies]
nextflow = "*"
fastqc = "0.12.1"
STAR = "2.7.11b"
coreutils = "9.1"
bc = "*"
