[project]
name = "nextflow-arm"
channels = ["conda-forge", "bioconda"]
platforms = ["linux-aarch64"]

[tasks]
default = "nextflow run main.nf -c nextflow.config"

[dependencies]
openjdk = "17"
nextflow = "*"
fastqc = "*"
star = "*"
