[project]
name = "tracer-arm"
channels = ["conda-forge", "bioconda"]
platforms = ["linux-arm64"]

[tasks]
setup = "pixi install"

[dependencies]
nextflow = "*"
openjdk = "17.*"
wget = "*"
star = ">=2.7.10"
fastqc = "*"
