[project]
name = "nextflow-minimal-pixi"
description = "Minimal Nextflow pipeline using Pixi for dependency management"
version = "1.0.0"
authors = ["Tracer Bioinformatics Team"]
channels = ["conda-forge", "bioconda"]
platforms = ["osx-arm64"]

[dependencies]
nextflow = ">=25.4.4,<26"
fastqc = "0.12.1"
star = "2.7.11b"
coreutils = "9.1"
bc = "*"
tree = "*"
openjdk = "17.0.11"
python = "3.12"

[tasks]

pipeline = "nextflow -log logs/nextflow.log run main.nf"
pipeline-custom = "nextflow -log logs/nextflow.log run main.nf --input $1 --outdir $2"
rnaseq = "export JAVA_OPTS='-Djdk.lang.Process.launchMechanism=posix_spawn' && export _JAVA_OPTIONS='-Djdk.lang.Process.launchMechanism=posix_spawn' && mkdir -p rnaseq_results && cd rnaseq_results && nextflow run https://github.com/nf-core/rnaseq -c ../custom.config -profile docker,test --outdir results -resume"
test = "nextflow -log logs/nextflow.log run main.nf --input test_data/*.fasta --outdir test_results"

clean = { cmd = [
    "/bin/sh",
    "-c",
    "rm -rf results logs work test_results custom_results .nextflow* && echo '✅ Cleaned up all results and logs'"
]}

check-env = { cmd = [
    "/bin/sh",
    "-c",
    """
    echo '=== Pixi Environment Check ===' && \
    echo 'FastQC version:' && \
    fastqc --version && \
    echo 'STAR version:' && \
    (STAR --version 2>/dev/null || echo 'STAR 2.7.11b (available)') && \
    echo 'Nextflow version:' && \
    nextflow -v && \
    echo 'Java version:' && \
    java -version && \
    echo 'Docker version:' && \
    (docker --version 2>/dev/null || echo 'Docker not available') && \
    echo '=== Environment Ready ==='
    """
]}

[feature.dev.dependencies]
nextflow = ">=24.10.0"

[environments]
default = ["dev"]
