receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:
    timeout: 10s
    send_batch_size: 1024

  memory_limiter:
    check_interval: 1s
    limit_mib: 512

  resource:
    attributes:
      - key: service.name
        value: tracer-airflow
        action: upsert

exporters:
  prometheus:
    endpoint: "0.0.0.0:8889"
    namespace: tracer-airflow
    const_labels:
      environment: docker-compose

  otlphttp/jaeger:
    endpoint: http://jaeger:4318
    tls:
      insecure: true
    retry_on_failure:
      enabled: true
      initial_interval: 5s
      max_interval: 30s
      max_elapsed_time: 300s

  otlphttp/tracer:
    # endpoint: "http://0.0.0.0:3000/api/public/otel-forward"
    endpoint: "http://host.docker.internal:3000/api/public/otel-forward"
    headers:
      Content-Type: "application/json"
    timeout: 60s
    retry_on_failure:
      enabled: true
      initial_interval: 10s
      max_interval: 60s
      max_elapsed_time: 600s
    sending_queue:
      enabled: true
      num_consumers: 2
      queue_size: 2000
    tls:
      insecure: true
    encoding: json
# Logging exporter for debugging

extensions:
  health_check:
    endpoint: 0.0.0.0:13133

  pprof:
    endpoint: 0.0.0.0:1777

service:
  extensions: [health_check, pprof]

  pipelines:
    traces:
      receivers: [otlp]
      processors: [memory_limiter, resource, batch]
      exporters: [otlphttp/jaeger, otlphttp/tracer]

    metrics:
      receivers: [otlp]
      processors: [memory_limiter, resource, batch]
      exporters: [prometheus, otlphttp/tracer]

  telemetry:
    logs:
      level: debug
    metrics:
      address: 0.0.0.0:8888
