name: linux-arm-ubuntu-minimal
channels:
  - conda-forge
  - bioconda
  - defaults

dependencies:
  - nextflow>=24.10.0
  - openjdk=17
  - fastqc=0.12.1
  - samtools=1.21
  - coreutils
  - bc
  - star
  - bwa
