name: nextflow-minimal
channels:
  - conda-forge
  - bioconda
  - defaults

dependencies:
  # Core tools
  - fastqc=0.12.1
  - coreutils=9.1
  - bc  # Calculator for arithmetic operations

  # Additional useful tools (optional)
  - seqkit=2.10.0  # For advanced FASTA manipulation
  - python=3.9
  - pip
  
  # Python packages via pip (optional)
  - pip:
    - biopython==1.81