[project]
name = "nextflow-minimal-pixi-linux-arm-ubuntu"
description = "Minimal Nextflow pipeline using Pixi for dependency management (Linux ARM Ubuntu)"
version = "1.0.0"
authors = ["Tracer Bioinformatics Team"]
channels = ["conda-forge", "bioconda"]
platforms = ["linux-aarch64"]

[dependencies]
nextflow = "24.10.0"
openjdk = "17.0.11"
python = "3.12"

grep = "*"
tar = "*"
coreutils = "*"
findutils = "*"

fastqc = "0.12.1"
star = "2.7.11b"
hisat2 = "2.2.1"
trim-galore = "0.6.10"
salmon = "1.10.3"
samtools = "1.21"
bbmap = "39.26"
fq = "0.12.0"
subread = "2.1.1"
picard = "*"
gawk = "*"
qualimap = "*"
stringtie = "*"
bedtools = "*"
ucsc-bedclip = "*"
ucsc-bedgraphtobigwig = "*"
bioconductor-dupradar = "*"
rseqc = "*"
multiqc = "*"
bioconductor-tximeta = "*"
bioconductor-tximport = "*"
bioconductor-summarizedexperiment = "*"
bioconductor-genomeinfodbdata = "*"
bioconductor-genomicranges = "*"
bioconductor-iranges = "*"
bioconductor-s4vectors = "*"
bioconductor-biocgenerics = "*"
bioconductor-genomeinfodb = "*"
gridss = ">=2.11.1,<3"


[tasks]
pipeline = "nextflow -log logs/nextflow.log run ../../shared/nextflow/main.nf --outdir results"
pipeline-custom = "nextflow -log logs/nextflow.log run main.nf --outdir $1"
test = "nextflow -log logs/nextflow.log run main.nf --outdir test_results"
rnaseq = "export JAVA_OPTS='-Djdk.lang.Process.launchMechanism=posix_spawn' && export _JAVA_OPTIONS='-Djdk.lang.Process.launchMechanism=posix_spawn' && mkdir -p rnaseq_results && cd rnaseq_results && nextflow run https://github.com/nf-core/rnaseq -r 3.14.0 -c ../../../shared/nextflow/custom.config -profile test --outdir results -resume"
rnaseq-1 = "export JAVA_OPTS='-Djdk.lang.Process.launchMechanism=posix_spawn' && export _JAVA_OPTIONS='-Djdk.lang.Process.launchMechanism=posix_spawn' && mkdir -p rnaseq_results && cd rnaseq_results && nextflow run https://github.com/nf-core/rnaseq -r 3.14.0 -c ../../../nextflow/config/custom.config -profile test --outdir results -resume"
rnaseq-2 = "export JAVA_OPTS='-Djdk.lang.Process.launchMechanism=posix_spawn' && export _JAVA_OPTIONS='-Djdk.lang.Process.launchMechanism=posix_spawn' && mkdir -p rnaseq_results && cd rnaseq_results && nextflow run https://github.com/nf-core/rnaseq -r 3.14.0 -c ../../../shared/nextflow/custom.config -profile test --outdir results -resume"
# rnaseq = "export JAVA_OPTS='-Djdk.lang.Process.launchMechanism=posix_spawn' && export _JAVA_OPTIONS='-Djdk.lang.Process.launchMechanism=posix_spawn' && nextflow -c ../../../shared/nextflow/config/local.config run -r 3.14.0 https://github.com/nf-core/rnaseq -params-file ../../nextflow/config/rnaseq-params.json --multiqc_config ../../../nextflow/config/custom_multiqc_config.yml -profile test"
# rnaseq = "export JAVA_OPTS='-Djdk.lang.Process.launchMechanism=posix_spawn' && export _JAVA_OPTIONS='-Djdk.lang.Process.launchMechanism=posix_spawn' && nextflow -c ../nextflow/config/local.config run -r 3.14.0 https://github.com/nf-core/rnaseq -params-file ../../nextflow/config/rnaseq-params.json --multiqc_config ../nextflow/config/custom_multiqc_config.yml -profile test"

clean = """
rm -rf results logs work test_results custom_results
rm -f .nextflow* 2>/dev/null || true
echo "Cleaned up all results and logs"
"""
check-env = """
echo "=== Pixi Environment Check ==="
echo "Java version:"
java -version
echo ""
echo "Nextflow version:"
nextflow -v
echo ""
echo "FastQC version:"
fastqc --version
echo ""
echo "STAR version:"
STAR --version 2>/dev/null || echo "STAR 2.7.11b (available)"
echo ""
echo "Samtools version:"
samtools --version | head -1
echo ""
echo "BWA version:"
bwa 2>&1 | head -3 | grep Version || echo "BWA 0.7.18 (available)"
echo ""
echo "GATK version:"
gatk --version | head -1 || echo "GATK4 4.6.1.0 (available)"
echo ""
echo "=== Environment Ready ==="
"""
dev = """
echo "=== Development Workflow ==="
pixi run clean
pixi run setup
pixi run check-env
pixi run test
echo "=== Development Workflow Complete ==="
"""
versions = "pixi run pipeline"
[feature.dev.dependencies]
nextflow = ">=24.10.0"
[environments]
default = ["dev"] 