[project]
name = "tracer-wdl"
channels = ["conda-forge", "bioconda"]
platforms = ["osx-arm64", "osx-64", "linux-64", "linux-aarch64"]

[dependencies]
python = "3.11.*"
miniwdl = "*"
samtools = "*"
star = "*"
fastqc = "*"
gffread = "*"
picard = "*"
openjdk = "*"
importlib_metadata = "<5"


[tasks]

script = "bash run.sh"
pipeline = "miniwdl run tracer_wdl_minimal.wdl -i tracer_wdl_minimal.inputs.json"
check = "STAR --runMode genomeGenerate --version && printf '@HD\tVN:1.0\n@SQ\tSN:chr1\tLN:1000\nr1\t0\tchr1\t1\t255\t1M\t*\t0\t0\tA\t*\n' | samtools view -S -"