[project]
name = "miniwdl-bio"
channels = ["conda-forge", "bioconda"]
platforms = ["osx-arm64", "osx-64", "linux-64", "linux-aarch64"]

[dependencies]
python = "*"
docker = "*"
miniwdl = "*"
samtools = "*"
star = "*"
fastqc = "*"
gffread = "*"
picard = "*"

[tasks]
pipeline = "pixi run miniwdl run tracer_wdl_minimal.wdl -i tracer_wdl_minimal.inputs.json"
