name: Codespaces pipelines

on:
  workflow_dispatch:
  push:
    paths:
      - "pipelines/codespaces/**"
      - ".github/workflows/codespaces.yml"
      - "pipelines/shared/wdl/**"
      - ".github/actions/**"

  schedule:
    - cron: "0 11 * * *"

jobs:
  wdl:
    name: Tracer WDL Minimal
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      TRACER_USER_ID: ${{ secrets.TRACER_USER_ID }}
      TRACER_TOKEN: ${{ secrets.TRACER_TOKEN }}

    steps:
      - uses: actions/checkout@v4

      - name: Install tracer
        run: |
          curl -sSL https://install.tracer.cloud | CLI_BRANCH=dev sh -s ${{ secrets.TRACER_USER_ID }}

      - name: Run a pipeline with tracer
        run: |
          tracer init --token ${{ secrets.TRACER_TOKEN }}

      - name: Run pipeline
        working-directory: pipelines/codespaces/wdl
        run: |
          ./run.sh

      - name: Verify tracer packages
        uses: ./.github/actions/verify-tracer
        with:
          is_ebpf: true
          use_sudo: true
          binary: tracer
          required_processes_ebpf: "samtools index, FastQC, samtools merge, samtools idxstats, samtools faidx, STAR align, samtools stats, samtools cat"

      - name: Upload pipeline results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: wdl-codespaces-pipeline-results
          path: |
            pipelines/codespaces/wdl/results/
            pipelines/codespaces/wdl/logs/
          retention-days: 7

  fastquorum:
    name: Fastquorum Pipeline
    runs-on: ubuntu-latest
    env:
      NXF_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      TRACER_USER_ID: ${{ secrets.TRACER_USER_ID }}
      TRACER_TOKEN: ${{ secrets.TRACER_TOKEN }}
    steps:
      - uses: actions/checkout@v4

      - name: Install tracer
        run: |
          curl -sSL https://install.tracer.cloud | CLI_BRANCH=dev sh -s ${{ secrets.TRACER_USER_ID }}

      - name: Run tracer init
        run: |
          tracer init --token ${{ secrets.TRACER_TOKEN }}

      - name: Run pipeline with Pixi
        working-directory: pipelines/codespaces/fastquorum
        run: |
          ./run.sh

      - name: Verify tracer packages
        uses: ./.github/actions/verify-tracer
        with:
          is_ebpf: true
          use_sudo: true
          binary: tracer
          required_processes_ebpf: "samtools dict, samtools faidx, bwa index, multiqc, samtools sort, samtools fastq, FastQC, bwa mem"

      - name: Upload pipeline results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: fastquorum-codespaces-pipeline-results
          path: |
            pipelines/codespaces/fastquorum/results/
            pipelines/codespaces/fastquorum/logs/
          retention-days: 7

  codespaces-pixi-test:
    name: Pixi Pipeline Test
    runs-on: ubuntu-latest
    env:
      TRACER_USER_ID: ${{ secrets.TRACER_USER_ID }}
      TRACER_TOKEN: ${{ secrets.TRACER_TOKEN }}
    steps:
      - uses: actions/checkout@v4

      - name: Install tracer
        run: |
          curl -sSL https://install.tracer.cloud | CLI_BRANCH=dev sh -s ${{ secrets.TRACER_USER_ID }}

      - name: Run tracer init
        run: |
          tracer init --token ${{ secrets.TRACER_TOKEN }}

      - name: Run pipeline with Pixi
        working-directory: pipelines/codespaces/nextflow-pixi
        run: |
          ./run.sh
      - name: Verify tracer packages
        uses: ./.github/actions/verify-tracer
        with:
          is_ebpf: true
          use_sudo: true
          binary: tracer
          required_processes_ebpf: "FastQC,samtools sort"

      - name: Upload pixi pipeline results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: codespaces-pixi-pipeline-results
          path: |
            pipelines/codespaces/nextflow-pixi/results/
            pipelines/codespaces/nextflow-pixi/logs/
          retention-days: 7

  codespaces-conda-test:
    name: Conda Pipeline Test
    runs-on: ubuntu-latest
    env:
      TRACER_USER_ID: ${{ secrets.TRACER_USER_ID }}
      TRACER_TOKEN: ${{ secrets.TRACER_TOKEN }}
    steps:
      - uses: actions/checkout@v4

      - name: Install tracer
        run: |
          curl -sSL https://install.tracer.cloud | CLI_BRANCH=dev sh -s ${{ secrets.TRACER_USER_ID }}

      - name: Run tracer init
        run: |
          tracer init --token ${{ secrets.TRACER_TOKEN }}

      - name: Run pipeline with Conda
        working-directory: pipelines/codespaces/nextflow-conda
        run: |
          ./run.sh

      - name: Verify tracer packages
        uses: ./.github/actions/verify-tracer
        with:
          is_ebpf: true
          use_sudo: true
          binary: tracer
          required_processes_ebpf: "samtools merge, STAR align, samtools sort, samtools flagstat, FastQC, samtools cat, samtools index, samtools idxstats, samtools faidx, samtools view, samtools stats"

      - name: Upload conda pipeline results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: codespaces-conda-pipeline-results
          path: |
            pipelines/codespaces/nextflow-conda/results/
            pipelines/codespaces/nextflow-conda/logs/
          retention-days: 7
