name: Codespaces Pipeline Test

on:
  workflow_dispatch:
  push:
    paths:
      - "pipelines/codespaces/**"
      - ".github/workflows/codespaces.yml"
  schedule:
    - cron: "0 13 * * *" # Daily at 13:00 UTC

jobs:
  codespaces-pixi-test:
    name: Pixi Pipeline Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run Codespaces Pixi pipeline
        working-directory: pipelines/codespaces/nextflow-pixi
        run: |
          echo "=== Running Codespaces Pixi Pipeline ==="
          bash run.sh

      - name: Verify pixi pipeline results
        working-directory: pipelines/codespaces/nextflow-pixi
        run: |
          echo "=== Verifying Pixi Pipeline Results ==="

          # Check if results were generated
          if [ -d "results" ]; then
            echo "✅ Results directory found"
            ls -la results/
            
            # Check for version check results
            if [ -f "results/tool_versions.txt" ]; then
              echo "✅ Tool versions file found"
              cat results/tool_versions.txt
            else
              echo "❌ Tool versions file not found"
              exit 1
            fi
          else
            echo "❌ Results directory not found"
            exit 1
          fi

          # Check if logs were generated
          if [ -d "logs" ]; then
            echo "✅ Logs directory found"
            ls -la logs/
          else
            echo "❌ Logs directory not found"
            exit 1
          fi

      - name: Upload pixi pipeline results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: codespaces-pixi-pipeline-results
          path: |
            pipelines/codespaces/nextflow-pixi/results/
            pipelines/codespaces/nextflow-pixi/logs/
          retention-days: 7

  codespaces-conda-test:
    name: Conda Pipeline Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run Codespaces Conda pipeline
        working-directory: pipelines/codespaces/nextflow-conda
        run: |
          echo "=== Running Codespaces Conda Pipeline ==="
          bash run.sh

      - name: Verify conda pipeline results
        working-directory: pipelines/codespaces/nextflow-conda
        run: |
          echo "=== Verifying Conda Pipeline Results ==="

          # Check if results were generated
          if [ -d "results" ]; then
            echo "✅ Results directory found"
            ls -la results/
            
            # Check for version check results
            if [ -f "results/tool_versions.txt" ]; then
              echo "✅ Tool versions file found"
              cat results/tool_versions.txt
            else
              echo "❌ Tool versions file not found"
              exit 1
            fi
          else
            echo "❌ Results directory not found"
            exit 1
          fi

          # Check if logs were generated
          if [ -d "logs" ]; then
            echo "✅ Logs directory found"
            ls -la logs/
          else
            echo "❌ Logs directory not found"
            exit 1
          fi

      - name: Upload conda pipeline results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: codespaces-conda-pipeline-results
          path: |
            pipelines/codespaces/nextflow-conda/results/
            pipelines/codespaces/nextflow-conda/logs/
          retention-days: 7

  cleanup:
    name: Cleanup
    runs-on: ubuntu-latest
    needs: [codespaces-pixi-test, codespaces-conda-test]
    if: always()
    steps:
      - uses: actions/checkout@v4

      - name: Clean up pixi environment
        working-directory: pipelines/codespaces/nextflow-pixi
        run: |
          echo "=== Cleaning up Pixi environment ==="
          if command -v pixi >/dev/null 2>&1; then
            export PATH="$HOME/.pixi/bin:$PATH"
            pixi run clean || true
          fi
          rm -rf results logs work .nextflow* 2>/dev/null || true
          echo "✅ Pixi cleanup completed"

      - name: Clean up conda environment
        working-directory: pipelines/codespaces/nextflow-conda
        run: |
          echo "=== Cleaning up Conda environment ==="
          rm -rf results logs work .nextflow* 2>/dev/null || true
          echo "✅ Conda cleanup completed"
