name: Codespaces pipelines

on:
  workflow_dispatch:
  push:
    paths:
      - "pipelines/codespaces/**"
      - ".github/workflows/codespaces.yml"
  schedule:
    - cron: "0 11 * * *"

jobs:
  fastquorum:
    name: Fastquorum Pipeline
    runs-on: ubuntu-latest
    env:
      TRACER_BIO: /root/.tracerbio/bin/tracer
      NXF_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4

      - name: Install tracer
        continue-on-error: true
        run: |
          curl -sSL https://install.tracer.cloud | sh && source ~/.bashrc

      - name: Run tracer init
        run: |
          sudo $TRACER_BIO init \
            --pipeline-name github-actions \
            --environment github-actions \
            --user-operator github-actions \
            --pipeline-type fastquorums \
            --is-dev true \

      - name: Run pipeline with Pixi
        working-directory: pipelines/codespaces/fastquorum
        run: |
          ./run.sh

      - name: Grep fgbio
        run: |
          grep -i "fgbio" /tmp/tracer/matches.txt

      - name: Verify tracer packages
        uses: ./.github/actions/verify-tracer
        with:
          is_ebpf: true
          use_sudo: true
          binary: $TRACER_BIO
          required_processes_ebpf: "multiqc, samtools dict, bwa, samtools fastq, FastQC, samtools sort, samtools faidx"

      - name: Upload pipeline results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: fastquorum-codespaces-pipeline-results
          path: |
            pipelines/codespaces/fastquorum/results/
            pipelines/codespaces/fastquorum/logs/
          retention-days: 7

  codespaces-pixi-test:
    name: Pixi Pipeline Test
    runs-on: ubuntu-latest
    env:
      TRACER_BIO: /root/.tracerbio/bin/tracer
    steps:
      - uses: actions/checkout@v4
      - name: Install tracer
        continue-on-error: true
        run: |
          curl -sSL https://install.tracer.cloud | CLI_BRANCH="update_fgbio_rules" sh && source ~/.bashrc

      - name: Run tracer init
        run: |
          sudo $TRACER_BIO init \
            --pipeline-name github-actions \
            --environment github-actions \
            --user-operator github-actions \
            --pipeline-type nextflow \
            --is-dev true

      - name: Run pipeline with Pixi
        working-directory: pipelines/codespaces/nextflow-pixi
        run: |
          ./run.sh

      - name: Grep fgbio
        run: |
          grep -i "STAR" /tmp/tracer/matches.txt

      - name: Verify tracer packages
        uses: ./.github/actions/verify-tracer
        with:
          is_ebpf: true
          use_sudo: true
          binary: $TRACER_BIO
          required_processes_ebpf: "FastQC,samtools sort"

      - name: Upload pixi pipeline results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: codespaces-pixi-pipeline-results
          path: |
            pipelines/codespaces/nextflow-pixi/results/
            pipelines/codespaces/nextflow-pixi/logs/
          retention-days: 7

  codespaces-conda-test:
    name: Conda Pipeline Test
    runs-on: ubuntu-latest
    env:
      TRACER_BIO: /root/.tracerbio/bin/tracer
    steps:
      - uses: actions/checkout@v4
      - name: Install tracer
        continue-on-error: true
        run: |
          curl -sSL https://install.tracer.cloud | CLI_BRANCH="update_fgbio_rules" sh && source ~/.bashrc

      - name: Run tracer init
        run: |
          sudo $TRACER_BIO init \
            --pipeline-name github-actions \
            --environment github-actions \
            --user-operator github-actions \
            --pipeline-type nextflow \
            --is-dev true

      - name: Run pipeline with Conda
        working-directory: pipelines/codespaces/nextflow-conda
        run: |
          ./run.sh

      - name: Grep fgbio
        run: |
          grep -i "STAR" /tmp/tracer/matches.txt

      - name: Verify tracer packages
        uses: ./.github/actions/verify-tracer
        with:
          is_ebpf: true
          use_sudo: true
          binary: $TRACER_BIO
          required_processes_ebpf: "samtools merge, STAR, samtools sort, samtools flagstat, FastQC, samtools cat, samtools index, samtools idxstats, samtools faidx, samtools view, samtools stats"

      - name: Upload conda pipeline results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: codespaces-conda-pipeline-results
          path: |
            pipelines/codespaces/nextflow-conda/results/
            pipelines/codespaces/nextflow-conda/logs/
          retention-days: 7
