name: Nextflow Linux x86_64 Amazon Linux Pipelines

on:
  workflow_dispatch:
  push:
    paths:
      - "pipelines/linux-x86-amazon-linux/**"
      - ".github/workflows/linux-x86-amazon-lin.yml"
  schedule:
    - cron: "0 11 * * *"

jobs:
  linux-x86-amazon-pixi:
    name: Pixi Pipeline
    runs-on: ubuntu-24.04
    env:
      TRACER_BIO: /root/.tracerbio/bin/tracer
    steps:
      - uses: actions/checkout@v4

      - name: Run pipeline in Amazon Linux Docker container
        run: |
          docker run --rm \
            --name tracer \
            --privileged \
            --pid=host \
            -v /lib/modules:/lib/modules:ro \
            -v /usr/src:/usr/src:ro \
            -v /sys/kernel/debug:/sys/kernel/debug:rw \
            -v /sys/kernel/btf/vmlinux:/sys/kernel/btf/vmlinux:ro \
            -v "${{ github.workspace }}":/workspace \
            -w /workspace \
            -e TRACER_BIO=/root/.tracerbio/bin/tracer \
            -e GITHUB_WORKSPACE=/workspace \
            -e GITHUB_SHA="${{ github.sha }}" \
            -e GITHUB_REF_NAME="${{ github.ref_name }}" \
            public.ecr.aws/amazonlinux/amazonlinux:2023 \
            bash -c "
              # Install system dependencies
              yum update -y
              yum install -y wget git bash which sudo tar gzip curl --allowerasing

              # Install tracer
              curl -sSL https://install.tracer.cloud/ | sudo bash

              # Run tracer init
              sudo \$TRACER_BIO init --pipeline-name github-actions --environment github-actions --user-operator github-actions --pipeline-type nextflow --is-dev true

              # Run pipeline with Pixi
              cd pipelines/linux-x86-amazon-linux/nextflow-pixi/
              export PATH=\"\$HOME/.pixi/bin:\$PATH\"
              echo '=== Running Nextflow Pipeline with Pixi ==='
              ./run.sh

              echo '=== Verifying tracer packages ==='
              cd ../../../
              chmod +x .github/actions/verify-tracer/action.sh
              .github/actions/verify-tracer/action.sh
            "


      - name: Upload pipeline results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: pixi-linux-x86-amazon-pipeline-results
          path: |
            pipelines/linux-x86-amazon-linux/nextflow-pixi/results/
            pipelines/linux-x86-amazon-linux/nextflow-pixi/logs/
          retention-days: 7

  linux-x86-amazon-conda:
    name: Conda Pipeline
    runs-on: ubuntu-24.04
    env:
      TRACER_BIO: /root/.tracerbio/bin/tracer
    steps:
      - uses: actions/checkout@v4

      - name: Run pipeline in Amazon Linux Docker container
        run: |
          docker run --rm \
            --name tracer \
            --privileged \
            --pid=host \
            -v /lib/modules:/lib/modules:ro \
            -v /usr/src:/usr/src:ro \
            -v /sys/kernel/debug:/sys/kernel/debug:rw \
            -v /sys/kernel/btf/vmlinux:/sys/kernel/btf/vmlinux:ro \
            -v "${{ github.workspace }}":/workspace \
            -w /workspace \
            -e TRACER_BIO=/root/.tracerbio/bin/tracer \
            -e GITHUB_WORKSPACE=/workspace \
            -e GITHUB_SHA="${{ github.sha }}" \
            -e GITHUB_REF_NAME="${{ github.ref_name }}" \
            public.ecr.aws/amazonlinux/amazonlinux:2023 \
            bash -c "
              # Install system dependencies
              yum update -y
              yum install -y wget git bash which sudo bzip2 tar gzip curl --allowerasing

              # Install tracer
              curl -sSL https://install.tracer.cloud/ | sudo bash
              echo '/root/.tracerbio/bin' | sudo tee -a \$GITHUB_PATH

              # Run tracer init
              sudo \$TRACER_BIO init --pipeline-name github-actions --environment github-actions --user-operator github-actions --pipeline-type nextflow --is-dev true

              # Run pipeline with Conda
              cd pipelines/linux-x86-amazon-linux/nextflow-conda
              ./run.sh

              echo '=== Verifying tracer packages ==='
              cd ../../../
              chmod +x .github/actions/verify-tracer/action.sh
              .github/actions/verify-tracer/action.sh
            "

      - name: Upload pipeline results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: conda-linux-x86-amazon-pipeline-results
          path: |
            pipelines/linux-x86-amazon-linux/nextflow-conda/results/
            pipelines/linux-x86-amazon-linux/nextflow-conda/logs/
          retention-days: 7

