name: Nextflow Linux x86_64 Amazon Linux Pipelines

on:
  workflow_dispatch:
  push:
    paths:
      - "pipelines/linux-x86-amazon-linux/**"
      - ".github/workflows/linux-x86-amazon-lin.yml"
  schedule:
    - cron: "0 11 * * *"

jobs:
  linux-x86-amazon-pixi:
    name: Pixi Pipeline
    runs-on: 
      - codebuild-nextflow-test-pipelines-amazon-linux-x86-${{ github.run_id }}-${{ github.run_attempt }}
    env:
      TRACER_BIO: /root/.tracerbio/bin/tracer
    steps:
      - name: Install system dependencies
        run: |
          sudo yum update -y --nogpgcheck
          yum install -y wget git bash which sudo tar gzip

      - uses: actions/checkout@v4

      - name: Cache Pixi environment
        uses: actions/cache@v4
        with:
          path: |
            pipelines/linux-x86-amazon-linux/.pixi
          key: pixi-linux-x86-amazon-${{ runner.os }}-${{ hashFiles('pipelines/linux-x86-amazon-linux/pixi.toml') }}
          restore-keys: |
            pixi-linux-x86-amazon-${{ runner.os }}-

      - name: Install tracer
        run: |
          curl -sSL https://install.tracer.cloud/ | sudo bash

      - name: Run tracer init
        run: |
          sudo $TRACER_BIO init --pipeline-name github-actions --environment github-actions --user-operator github-actions --pipeline-type nextflow --is-dev true

      - name: Run pipeline with Pixi
        working-directory: pipelines/linux-x86-amazon-linux/nextflow-pixi
        run: |
          ./run.sh

      - name: Verify tracer packages
        uses: ./.github/actions/verify-tracer
        with:
          required_processes: "STAR,FastQC,samtools sort"
          sleep_duration: 10
          use_sudo: true
          binary: $TRACER_BIO

      - name: Upload pipeline results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: pixi-linux-x86-amazon-pipeline-results
          path: |
            pipelines/linux-x86-amazon-ubuntu/nextflow-pixi/results/
            pipelines/linux-x86-amazon-ubuntu/nextflow-pixi/logs/
          retention-days: 7

  linux-x86-amazon-conda:
    name: Conda Pipeline
    runs-on: 
      - codebuild-nextflow-test-pipelines-amazon-linux-x86-${{ github.run_id }}-${{ github.run_attempt }}
    env:
      TRACER_BIO: /root/.tracerbio/bin/tracer

    steps:
      - name: Install system dependencies
        run: |
          sudo yum update -y --nogpgcheck
          yum install -y wget git bash which sudo bzip2 tar gzip

      - uses: actions/checkout@v4

      - name: Install tracer
        run: |
          curl -sSL https://install.tracer.cloud/ | sudo bash
          echo "/root/.tracerbio/bin" | sudo tee -a $GITHUB_PATH

      - name: Run tracer init
        run: |
          sudo $TRACER_BIO init --pipeline-name github-actions --environment github-actions --user-operator github-actions --pipeline-type nextflow --is-dev true

     
      - name: Run pipeline with Conda
        working-directory: pipelines/linux-x86-amazon-linux/nextflow-conda
        run: |
           ./run.sh

      - name: Verify tracer packages
        uses: ./.github/actions/verify-tracer
        with:
          required_processes: "STAR,FastQC,samtools sort"
          sleep_duration: 10
          use_sudo: true
          binary: $TRACER_BIO

      - name: Upload pipeline results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: conda-linux-x86-amazon-pipeline-results
          path: |
            pipelines/linux-x86-amazon-linux/nextflow-conda/results/
          retention-days: 7
