name: Nextflow Linux x86_64 Ubuntu Pipelines

on:
  workflow_dispatch:
  push:
    paths:
      - "pipelines/linux-x86-ubuntu/nextflow-pixi/**"
      - "pipelines/linux-x86-ubuntu/nextflow-conda/**"
      - ".github/workflows/linux-x86_64-ubuntu.yml"
  schedule:
    - cron: "0 11 * * *"
    # Daily at 11:00 UTC

jobs:
  linux-x86-pixi:
    name: Pixi Pipeline
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install tracer
        uses: ./.github/actions/tracer-client
        with:
          tracer_user_id: ${{ secrets.ACTIONS_TRACER_USER_ID }}

      - name: Run tracer init
        run: |
          sudo tracer init \
          --pipeline-name github-actions \
          --environment github-actions \
          --user-operator github-actions \
          --pipeline-type nextflow \
          --is-dev true
      - name: Run pipeline with Pixi
        working-directory: pipelines/linux-x86-ubuntu/nextflow-pixi
        run: |
          echo "=== Running Nextflow Pipeline with Pixi ==="
          ./run.sh
      - name: Verify tracer packages
        uses: ./.github/actions/verify-tracer
        with:
          is_ebpf: true
          use_sudo: true
          binary: tracer

      - name: Upload pipeline results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: pixi-linux-x86-pipeline-results
          path: |
            pipelines/linux-x86-ubuntu/nextflow-pixi/results/
            pipelines/linux-x86-ubuntu/nextflow-pixi/logs/
          retention-days: 7

  linux-x86-conda:
    name: Conda Pipeline
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install tracer
        uses: ./.github/actions/tracer-client
        with:
          tracer_user_id: ${{ secrets.ACTIONS_TRACER_USER_ID }}

      - name: Run tracer init
        run: |
          sudo tracer init \
          --pipeline-name github-actions \
          --environment github-actions \
          --user-operator github-actions \
          --pipeline-type nextflow \
          --is-dev true
      - name: Run pipeline with Conda
        working-directory: pipelines/linux-x86-ubuntu/nextflow-conda
        run: |
          echo "=== Running Nextflow Pipeline with Conda ==="
          ./run.sh

      - name: Verify tracer packages
        uses: ./.github/actions/verify-tracer
        with:
          is_ebpf: true
          use_sudo: true
          binary: tracer

      - name: Upload pipeline results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: conda-linux-x86-pipeline-results
          path: |
            pipelines/linux-x86-ubuntu/nextflow-conda/results/
          retention-days: 7
