name: Nextflow Linux x86_64 Amazon Linux Pipelines

on:
  workflow_dispatch:
  push:
    paths:
      - "pipelines/linux-x86-amazon-linux/**"
      - ".github/workflows/linux-x86-amazon-lin.yml"
      - ".github/actions/verify-tracer/action.sh"
  schedule:
    - cron: "0 11 * * *"

jobs:
  linux-x86-amazon-pixi:
    name: Pixi Pipeline
    runs-on: ubuntu-24.04
    container:
      image: amazonlinux:2023
    steps:
      - name: Install system dependencies
        run: |
          yum update -y
          yum install -y wget git bash which tar gzip curl bzip2 --allowerasing
      - uses: actions/checkout@v4
      - name: Install tracer
        uses: ./.github/actions/install-tracer
        with:
          tracer_user_id: ${{ secrets.TRACER_USER_ID }}

      - name: Initialize tracer
        run: |
          tracer init --pipeline-name github-actions \
           --environment github-actions \
           --user-id github-actions \
           --pipeline-type nextflow
      - name: Run Pixi pipeline
        run: |
          cd pipelines/linux-x86-amazon-linux/nextflow-pixi/
          ./run.sh
      - name: Verify tracer packages
        run: |
          chmod +x .github/actions/verify-tracer/action.sh
          .github/actions/verify-tracer/action.sh
      - name: Upload pipeline results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: pixi-linux-x86-amazon-pipeline-results
          path: |
            pipelines/linux-x86-amazon-linux/nextflow-pixi/results/
            pipelines/linux-x86-amazon-linux/nextflow-pixi/logs/
          retention-days: 7

  linux-x86-amazon-conda:
    name: Conda Pipeline
    runs-on: ubuntu-24.04
    container:
      image: amazonlinux:2023
    steps:
      - name: Install system dependencies
        run: |
          yum update -y
          yum install -y wget git bash which bzip2 tar gzip curl --allowerasing
      - uses: actions/checkout@v4
      - name: Install tracer
        uses: ./.github/actions/install-tracer
        with:
          tracer_user_id: ${{ secrets.TRACER_USER_ID }}
      - name: Initialize tracer
        run: |
          tracer init --pipeline-name github-actions \
           --environment github-actions \
           --user-id github-actions \
           --pipeline-type nextflow
      - name: Run Conda pipeline
        run: |
          cd pipelines/linux-x86-amazon-linux/nextflow-conda
          ./run.sh
      - name: Verify tracer packages
        run: |
          chmod +x .github/actions/verify-tracer/action.sh
          .github/actions/verify-tracer/action.sh
      - name: Upload pipeline results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: conda-linux-x86-amazon-pipeline-results
          path: |
            pipelines/linux-x86-amazon-linux/nextflow-conda/results/
            pipelines/linux-x86-amazon-linux/nextflow-conda/logs/
          retention-days: 7
