name: Nextflow Linux ARM64 Amazon Linux Pipelines

on:
  workflow_dispatch:
  push:
    paths:
      - "pipelines/linux-arm-amazon-linux/**"
      - ".github/workflows/linux-aarch64-amazon-lin.yml"
  schedule:
    - cron: "0 11 * * *" # Daily at 11:00 UTC

jobs:
  linux-arm64-amazon-pixi:
    name: Pixi Pipeline
    runs-on: ubuntu-24.04-arm
    container:
      image: public.ecr.aws/amazonlinux/amazonlinux:2023
    steps:
      - name: Install system dependencies
        run: |
          yum update -y
          yum install -y wget git bash which sudo tar gzip --allowerasing

      - uses: actions/checkout@v4

      - name: Install Pixi
        run: |
          curl -fsSL https://pixi.sh/install.sh | bash
          echo "$HOME/.pixi/bin" >> $GITHUB_PATH
      - name: Install Tracer Client
        uses: ./.github/actions/tracer-client

      - name: Run tracer init
        run: |
          tracer init --pipeline-name github-actions --environment github-actions --user-operator github-actions --pipeline-type nextflow --is-dev true

      - name: Run pipeline with Pixi
        working-directory: pipelines/linux-arm-amazon-linux/nextflow-pixi
        run: |
          export PATH="$HOME/.pixi/bin:$PATH"
          ./run.sh

      - name: Verify tracer packages
        uses: ./.github/actions/verify-tracer
        with:
          required_processes: "STAR,FastQC,samtools sort"
          sleep_duration: 10
          use_sudo: true
          binary: tracer

      - name: Upload pipeline results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: pixi-linux-arm64-amazon-pipeline-results
          path: |
            pipelines/linux-arm-amazon-linux/nextflow-pixi/results/
          retention-days: 7

  linux-arm64-amazon-conda:
    name: Conda Pipeline
    runs-on: ubuntu-24.04-arm
    container:
      image: public.ecr.aws/amazonlinux/amazonlinux:2023
    steps:
      - name: Install system dependencies
        run: |
          yum update -y
          yum install -y wget git bash which sudo bzip2 tar gzip --allowerasing
      - uses: actions/checkout@v4
      - name: Install Tracer Client
        uses: ./.github/actions/tracer-client
        with:
          tracer_user_id: ${{ secrets.TRACER_USER_ID }}

      - name: Run tracer init
        run: |
          tracer init --pipeline-name github-actions --environment github-actions --user-operator github-actions --pipeline-type nextflow --is-dev true

      - name: Run pipeline with Conda
        working-directory: pipelines/linux-arm-amazon-linux/nextflow-conda
        run: |
          ./run.sh

      - name: Verify tracer packages
        uses: ./.github/actions/verify-tracer
        with:
          required_processes: "STAR,FastQC,samtools sort"
          sleep_duration: 10
          use_sudo: true
          binary: tracer
      - name: Upload pipeline results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: conda-linux-arm64-amazon-pipeline-results
          path: |
            pipelines/linux-arm-amazon-linux/nextflow-conda/results/
          retention-days: 7
