name: Nextflow Linux ARM64 Pipelines

on:
  workflow_dispatch:
  push:
    paths:
      - "pipelines/linux-arm-ubuntu/**"
      - ".github/workflows/linux-aarch64.yml"
  schedule:
    - cron: "0 11 * * *" # Daily at 11:00 UTC

jobs:
  linux-arm64-pixi:
    name: Pixi Pipeline
    runs-on: ubuntu-24.04-arm
    env:
      TRACER_BIO: /root/.tracerbio/bin/tracer
    steps:
      - uses: actions/checkout@v4

      - name: Install Pixi
        run: |
          curl -fsSL https://pixi.sh/install.sh | bash
          echo "$HOME/.pixi/bin" >> $GITHUB_PATH

      - name: Cache Pixi environment
        uses: actions/cache@v4
        with:
          path: |
            pipelines/linux-arm-ubuntu/.pixi
          key: pixi-linux-arm64-${{ runner.os }}-${{ hashFiles('pipelines/linux-arm-ubuntu/pixi.toml') }}
          restore-keys: |
            pixi-linux-arm64-${{ runner.os }}-

      - name: Install Pixi dependencies
        working-directory: pipelines/linux-arm-ubuntu/nextflow-pixi
        run: |
          export PATH="$HOME/.pixi/bin:$PATH"
          pixi install || true

      - name: Install tracer
        continue-on-error: true
        run: |
          curl -sSL https://install.tracer.cloud | bash || echo "Tracer installation failed"

      - name: Run tracer init
        run: |
          sudo $TRACER_BIO init --pipeline-name github-actions --environment github-actions --user-operator github-actions --pipeline-type nextflow --is-dev true

      - name: Run pipeline with Pixi
        working-directory: pipelines/linux-arm-ubuntu/nextflow-pixi
        run: |
          export PATH="$HOME/.pixi/bin:$PATH"
          echo "=== Running Nextflow Pipeline with Pixi ==="
          ./run.sh

      - name: Verify tracer packages
        uses: ./.github/actions/verify-tracer
        with:
          required_processes: "STAR,FastQC,salmon,samtools"
          sleep_duration: "10"
          use_sudo: "true"
          tracer_binary: "${{ env.TRACER_BIO }}"

      - name: Upload pipeline results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: pixi-linux-arm64-pipeline-results
          path: |
            pipelines/linux-arm-ubuntu/nextflow-pixi/results/
          retention-days: 7

  linux-arm64-conda:
    name: Conda Pipeline
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@v4

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: 3.12
          miniforge-variant: Miniforge3
          miniforge-version: latest

      - name: Install Nextflow
        run: |
          curl -s https://get.nextflow.io | bash
          sudo mv nextflow /usr/local/bin/

      - name: Install Conda environment
        working-directory: pipelines/linux-arm-ubuntu/nextflow-conda
        run: |
          mamba env create -f environment-minimal.yml || conda env create -f environment-minimal.yml || true
          source ~/miniconda3/etc/profile.d/conda.sh

      - name: Install tracer
        continue-on-error: true
        run: |
          curl -sSL https://install.tracer.cloud | bash || echo "Tracer installation failed"

      - name: Run tracer init
        run: |
          sudo $TRACER_BIO init --pipeline-name github-actions --environment github-actions --user-operator github-actions --pipeline-type nextflow --is-dev true

      - name: Run pipeline with Conda
        working-directory: pipelines/linux-arm-ubuntu/nextflow-conda
        run: |
          source ~/miniconda3/etc/profile.d/conda.sh
          ./run.sh

      - name: Verify tracer packages
        uses: ./.github/actions/verify-tracer
        with:
          required_processes: "STAR,FastQC,salmon,samtools"
          sleep_duration: "10"
          use_sudo: "true"
          tracer_binary: "${{ env.TRACER_BIO }}"

      - name: Upload pipeline results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: conda-linux-arm64-pipeline-results
          path: |
            pipelines/linux-arm-ubuntu/nextflow-conda/results/
          retention-days: 7
