name: Linux x86_64 Ubuntu pipelines

on:
  workflow_dispatch:
  push:
    paths:
      - "pipelines/linux-x86-ubuntu/**"
      - ".github/workflows/linux-x86_64-ubuntu.yml"
  schedule:
    - cron: "*/2 * * * *"

jobs:
  wdl:
    name: Tracer WDL Minimal
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Tracer
        run: |
          curl -sSL https://install.tracer.cloud/ | sudo bash  && source ~/.bashrc && source ~/.profile

      - name: Run tracer init
        run: |
          sudo $TRACER_BIO init \
            --pipeline-name github-actions \
            --environment github-actions \
            --user-operator github-actions \
            --pipeline-type nextflow \
            --is-dev true
      - name: Run pipeline
        working-directory: pipelines/linux-x86-ubuntu/wdl
        run: |
          ./run.sh

      - name: Verify tracer packages
        uses: ./.github/actions/verify-tracer
        with:
          is_ebpf: true
          use_sudo: true
          binary: $TRACER_BIO
          required_processes_ebpf: "samtools index, FastQC, samtools merge, samtools view, samtools idxstats, samtools faidx, STAR, samtools stats, samtools cat"

      - name: Upload pipeline results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: wdl-linux-x86-ubuntu-pipeline-results
          path: |
            pipelines/linux-x86-ubuntu/wdl/results/
            pipelines/linux-x86-ubuntu/wdl/logs/
          retention-days: 7

  fastquorum:
    name: Fastquorum Linux x86_64 Ubuntu
    runs-on: ubuntu-latest
    env:
      TRACER_BIO: /root/.tracerbio/bin/tracer
      NXF_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - name: Install tracer
        run: |
          curl -sSL https://install.tracer.cloud/ | sudo bash
          echo "/root/.tracerbio/bin" | sudo tee -a $GITHUB_PATH

      - name: Run tracer init
        run: |
          sudo $TRACER_BIO init \
            --pipeline-name github-actions \
            --environment github-actions \
            --user-operator github-actions \
            --pipeline-type nextflow \
            --is-dev true

      - name: Run pipeline with Pixi
        working-directory: pipelines/linux-x86-ubuntu/fastquorum
        run: |
          ./run.sh

      - name: Verify tracer packages
        uses: ./.github/actions/verify-tracer
        with:
          is_ebpf: true
          use_sudo: true
          binary: $TRACER_BIO
          required_processes_ebpf: "multiqc, samtools dict, bwa, samtools fastq, FastQC, samtools sort, samtools faidx"

      - name: Upload pipeline results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: fastquorum-linux-x86-ubuntu-pipeline-results
          path: |
            pipelines/linux-x86-ubuntu/fastquorum/results/
            pipelines/linux-x86-ubuntu/fastquorum/logs/
          retention-days: 7

  linux-x86-pixi:
    name: Pixi Pipeline
    runs-on: ubuntu-latest
    env:
      TRACER_BIO: /root/.tracerbio/bin/tracer
    steps:
      - uses: actions/checkout@v4

      - name: Install tracer
        run: |
          curl -sSL https://install.tracer.cloud | sudo bash

      - name: Run tracer init
        run: |
          sudo $TRACER_BIO init \
            --pipeline-name github-actions \
            --environment github-actions \
            --user-operator github-actions \
            --pipeline-type nextflow \
            --is-dev true

      - name: Run pipeline with Pixi
        working-directory: pipelines/linux-x86-ubuntu/nextflow-pixi
        run: |
          ./run.sh
      - name: Verify tracer packages
        uses: ./.github/actions/verify-tracer
        with:
          is_ebpf: true
          use_sudo: true
          binary: $TRACER_BIO
          required_processes_ebpf: "STAR,FastQC,samtools sort"
          required_processes_polling: "STAR,FastQC,salmon"

      - name: Upload pipeline results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: pixi-linux-x86-pipeline-results
          path: |
            pipelines/linux-x86-ubuntu/nextflow-pixi/results/
            pipelines/linux-x86-ubuntu/nextflow-pixi/logs/
          retention-days: 7

  linux-x86-conda:
    name: Conda Pipeline
    runs-on: ubuntu-latest
    env:
      TRACER_BIO: /root/.tracerbio/bin/tracer
    steps:
      - uses: actions/checkout@v4
      - name: Install tracer
        run: |
          curl -sSL https://install.tracer.cloud | sudo bash

      - name: Run tracer init
        run: |
          sudo $TRACER_BIO init \
            --pipeline-name github-actions \
            --environment github-actions \
            --user-operator github-actions \
            --pipeline-type nextflow \
            --is-dev true

      - name: Run pipeline with Conda
        working-directory: pipelines/linux-x86-ubuntu/nextflow-conda
        run: |
          ./run.sh

      - name: Verify tracer packages
        uses: ./.github/actions/verify-tracer
        with:
          is_ebpf: true
          use_sudo: true
          binary: $TRACER_BIO
          required_processes_ebpf: "STAR,FastQC,samtools sort"
          required_processes_polling: "STAR,FastQC,salmon"

      - name: Upload pipeline results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: conda-linux-x86-pipeline-results
          path: |
            pipelines/linux-x86-ubuntu/nextflow-conda/results/
          retention-days: 7
