name: Nextflow Linux x86_64 Amazon Linux Pipelines

on:
  workflow_dispatch:
  push:
    paths:
      - "pipelines/linux-x86-amazon-linux/**"
      - ".github/workflows/linux-x86-amazon-lin.yml"
  schedule:
    - cron: "0 11 * * *"

jobs:
  setup-tracer:
    name: Setup Tracer on Ubuntu Host
    runs-on: ubuntu-24.04
    steps:
      - name: Install tracer on Ubuntu
        run: |
          curl -sSL https://install.tracer.cloud/ | bash
          echo "Tracer installed at: $HOME/.tracerbio/bin/tracer"

      - name: Initialize tracer
        run: |
          $HOME/.tracerbio/bin/tracer init --pipeline-name github-actions \
            --environment github-actions \
            --user-operator github-actions \
            --pipeline-type nextflow \
            --is-dev true
          echo "Tracer initialized on Ubuntu host"

  linux-x86-amazon-pixi:
    name: Pixi Pipeline
    runs-on: ubuntu-24.04
    needs: setup-tracer
    env:
      TRACER_BIO: /home/runner/.tracerbio/bin/tracer
    container:
      image: public.ecr.aws/amazonlinux/amazonlinux:2023
      options: --pid=host --privileged
    steps:
      - name: Install system dependencies
        run: |
          yum update -y
          yum install -y wget git bash which sudo tar gzip --allowerasing

      - uses: actions/checkout@v4

      - name: Cache Pixi environment
        uses: actions/cache@v4
        with:
          path: |
            pipelines/linux-x86-amazon-linux/.pixi
          key: pixi-linux-x86-amazon-${{ runner.os }}-${{ hashFiles('pipelines/linux-x86-amazon-linux/pixi.toml') }}
          restore-keys: |
            pixi-linux-x86-amazon-${{ runner.os }}-



      - name: Run pipeline with Pixi
        working-directory: pipelines/linux-x86-amazon-linux/nextflow-pixi
        run: |
          ./run.sh

      - name: Verify tracer packages
        uses: ./.github/actions/verify-tracer
        with:
          required_processes: "STAR,FastQC,samtools sort"
          sleep_duration: 10
          use_sudo: true
          binary: $TRACER_BIO

      - name: Upload pipeline results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: pixi-linux-x86-amazon-pipeline-results
          path: |
            pipelines/linux-x86-amazon-ubuntu/nextflow-pixi/results/
            pipelines/linux-x86-amazon-ubuntu/nextflow-pixi/logs/
          retention-days: 7

  linux-x86-amazon-conda:
    name: Conda Pipeline
    runs-on: ubuntu-24.04
    needs: setup-tracer
    env:
      TRACER_BIO: /home/runner/.tracerbio/bin/tracer
    container:
      image: public.ecr.aws/amazonlinux/amazonlinux:2023
      options: --pid=host --privileged
    steps:
      - name: Install system dependencies
        run: |
          yum update -y
          yum install -y wget git bash which sudo bzip2 tar gzip --allowerasing

      - uses: actions/checkout@v4



     
      - name: Run pipeline with Conda
        working-directory: pipelines/linux-x86-amazon-linux/nextflow-conda
        run: |
           ./run.sh

      - name: Verify tracer packages
        uses: ./.github/actions/verify-tracer
        with:
          required_processes: "STAR,FastQC,samtools sort"
          sleep_duration: 10
          use_sudo: true
          binary: $TRACER_BIO

      - name: Upload pipeline results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: conda-linux-x86-amazon-pipeline-results
          path: |
            pipelines/linux-x86-amazon-linux/nextflow-conda/results/
          retention-days: 7
