name: Nextflow Conda MacOS ARM64 Pipeline

on:
  workflow_dispatch:
  push:
    paths:
    - 'pipelines/macos-arm64/nextflow-conda/**'
    - '.github/workflows/mac-arm64.yml'
  schedule:
  - cron: '0 11 * * *' # Daily at 11:00 UTC (12:00 BST)

jobs:
  setup-and-run-pipeline:
    runs-on: macos-14
    defaults:
      run:
        shell: bash -l {0}
    steps:
    - uses: actions/checkout@v4

    - name: Cache Conda environment and Nextflow
      id: cache-env
      uses: actions/cache@v4
      with:
        path: |
          ~/miniconda
          /usr/local/bin/nextflow
        key: ${{ runner.os }}-miniconda-nextflow-arm64-stable

    - name: Set up Miniconda
      if: steps.cache-env.outputs.cache-hit != 'true'
      env:
        PYTHONWARNINGS: "ignore::DeprecationWarning"
      uses: conda-incubator/setup-miniconda@v3
      with:
        miniconda-version: "latest"
        architecture: arm64
        auto-update-conda: true
        auto-activate-base: false

    - name: Install Nextflow
      if: steps.cache-env.outputs.cache-hit != 'true'
      run: |
        curl -s https://get.nextflow.io | bash
        sudo mv nextflow /usr/local/bin/

    - name: Verify installations
      run: |
        conda --version
        nextflow -v

    - name: Install tracer
      continue-on-error: true
      run: |
        echo "Installing tracer..."
        curl -sSL https://install.tracer.cloud/ | bash

        # Source shell config files to get updated PATH
        source ~/.bashrc 2>/dev/null || true
        source ~/.bash_profile 2>/dev/null || true
        source ~/.zshrc 2>/dev/null || true
        source ~/.profile 2>/dev/null || true

        # Find where tracer was actually installed
        TRACER_DIRS=("$HOME/bin" "$HOME/.local/bin" "$HOME/.tracerbio/bin")
        TRACER_FOUND=""

        for dir in "${TRACER_DIRS[@]}"; do
          if [ -f "$dir/tracer" ]; then
            echo "✅ Found tracer at: $dir/tracer"
            TRACER_FOUND="$dir"
            break
          fi
        done

        # Add all potential tracer directories to GitHub Actions PATH
        echo "$HOME/bin" >> $GITHUB_PATH
        echo "$HOME/.local/bin" >> $GITHUB_PATH
        echo "$HOME/.tracerbio/bin" >> $GITHUB_PATH

        # Also create a tracer wrapper script in a known location
        if [ -n "$TRACER_FOUND" ]; then
          echo "Creating tracer wrapper in /usr/local/bin..."
          sudo ln -sf "$TRACER_FOUND/tracer" /usr/local/bin/tracer || true
          echo "/usr/local/bin" >> $GITHUB_PATH
        fi

        # Test tracer availability
        export PATH="$HOME/bin:$HOME/.local/bin:$HOME/.tracerbio/bin:/usr/local/bin:$PATH"
        if command -v tracer &> /dev/null; then
          echo "✅ Tracer is available in PATH"
          tracer --version || echo "Tracer version check failed but command exists"
        else
          echo "❌ Tracer still not found in PATH"
        fi

    - name: Run tracer init
      run: |
        # Ensure tracer is in PATH
        export PATH="$HOME/bin:$HOME/.local/bin:$HOME/.tracerbio/bin:/usr/local/bin:$PATH"

        # Verify tracer is available
        if command -v tracer &> /dev/null; then
          echo "✅ Tracer found: $(which tracer)"
          tracer init --pipeline-name github-actions --environment github-actions --user-operator github-actions --pipeline-type nextflow --is-dev true
        else
          echo "❌ Tracer not found in PATH"
          echo "Current PATH: $PATH"
          echo "Searching for tracer binary..."
          find /Users/runner -name "tracer" -type f 2>/dev/null || echo "No tracer binary found"
          exit 1
        fi

    - name: Run pipeline
      working-directory: pipelines/macos-arm64/nextflow-conda
      run: |
        # Initialize conda properly
        if [ -f "$HOME/miniconda3/etc/profile.d/conda.sh" ]; then
          source "$HOME/miniconda3/etc/profile.d/conda.sh"
        elif [ -f "/Users/runner/miniconda3/etc/profile.d/conda.sh" ]; then
          source "/Users/runner/miniconda3/etc/profile.d/conda.sh"
        fi

        # Ensure conda is in PATH
        export PATH="$HOME/miniconda3/bin:/Users/runner/miniconda3/bin:$PATH"

        # Initialize conda for this shell
        conda init bash 2>/dev/null || true

        # Verify conda is available
        if command -v conda &> /dev/null; then
          echo "✅ Conda found: $(which conda)"
          conda --version
          conda info --envs
        else
          echo "❌ Conda not found in PATH"
          echo "Current PATH: $PATH"
          echo "Searching for conda..."
          find /Users/runner -name "conda" -type f 2>/dev/null | head -5
          exit 1
        fi

        # Run the pipeline
        bash run.sh

    - name: Run tracer INFO to verify that the right packages have been installed
      run: |
        # Ensure tracer is in PATH
        export PATH="$HOME/bin:$HOME/.local/bin:$HOME/.tracerbio/bin:/usr/local/bin:$PATH"

        # Verify tracer is available
        if command -v tracer &> /dev/null; then
          echo "✅ Tracer found: $(which tracer)"
          tracer info
        else
          echo "❌ Tracer not found in PATH"
          echo "Current PATH: $PATH"
          echo "Searching for tracer binary..."
          find /Users/runner -name "tracer" -type f 2>/dev/null || echo "No tracer binary found"
          exit 1
        fi
