name: Nextflow Conda MacOS ARM64 Pipeline

on:
  workflow_dispatch:
  push:
    paths:
    - 'pipelines/macos-arm64/nextflow-conda/**'
    - '.github/workflows/mac-arm64.yml'
  schedule:
  - cron: '0 11 * * *' # Daily at 11:00 UTC (12:00 BST)

jobs:
  setup-and-run-pipeline:
    runs-on: macos-14
    defaults:
      run:
        shell: bash -l {0}
    steps:
    - uses: actions/checkout@v4

    - name: Set up Miniconda
      env:
        PYTHONWARNINGS: "ignore::DeprecationWarning"
      uses: conda-incubator/setup-miniconda@v3
      with:
        miniconda-version: "latest"
        architecture: arm64
        auto-update-conda: true
        auto-activate-base: false

    - name: Install Nextflow
      run: |
        curl -s https://get.nextflow.io | bash
        sudo mv nextflow /usr/local/bin/

    - name: Verify installations
      run: |
        conda --version
        nextflow -v

    - name: Install tracer
      continue-on-error: true
      run: |
        echo "Installing tracer..."
        sudo curl -sSL https://install.tracer.cloud/binary-installer.sh  | bash -s ci_cd_user_123 && source ~/.bashrc

        TRACER_PATH=$(find ~ -name tracer -type f | head -n1)
        if [[ -n "$TRACER_PATH" ]]; then
          echo "✅ Found tracer at: $TRACER_PATH"
          mkdir -p ~/bin
          ln -sf "$TRACER_PATH" ~/bin/tracer
        else
          echo "❌ Tracer installation failed."
          exit 1
        fi

        echo "$HOME/bin" >> $GITHUB_PATH

    - name: Run tracer init
      run: |
        sudo tracer init --pipeline-name github-actions --environment github-actions --user-operator github-actions --pipeline-type nextflow --is-dev true

    - name: Run pipeline
      working-directory: pipelines/macos-arm64/nextflow-conda
      run: |
        source ~/miniconda3/etc/profile.d/conda.sh
        conda init bash
        bash run.sh

    - name: Verify tracer packages
      run: |
        sudo tracer info
