name: Nextflow Conda MacOS ARM64 Pipeline

on:
  workflow_dispatch:
  push:
    paths:
      - 'pipelines/nextflow-conda-macos-arm64/**'
      - '.github/workflows/mac-arm64.yml'

jobs:
  test:
    runs-on: macos-14
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          miniconda-version: "latest"     # or pin e.g. "py312_24.3.0-0"
          architecture: arm64
          auto-update-conda: true
          auto-activate-base: false
      - name: Install Nextflow
        run: |
          curl -s https://get.nextflow.io | bash
          sudo mv nextflow /usr/local/bin/
      - name: Run pipeline
        working-directory: pipelines/nextflow-conda-macos-arm64
        run: |
          bash run.sh
