name: macOS arm64 pipelines

on:
  workflow_dispatch:
  push:
    paths:
      - "pipelines/macos-arm64/**"
      - ".github/workflows/macos-arm64.yml"
      - ".github/actions/verify-tracer/action.yml"
      - ".github/actions/install-tracer/action.yml"
  schedule:
    - cron: "0 11 * * *"

permissions:
  contents: read
  packages: read

jobs:
  fastquorum-pixi:
    name: Fastquorum macOS arm64
    runs-on: macos-14
    env:
      NXF_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      TRACER_USER_ID: ${{ secrets.TRACER_USER_ID }}
      TRACER_TOKEN: ${{ secrets.TRACER_TOKEN }}
    steps:
      - uses: actions/checkout@v4

      # - name: Install tracer
      #   uses: ./.github/actions/install-tracer
      #   with:
      #     tracer_user_id: ${{ secrets.TRACER_USER_ID }}
      - name: Install tracer
        run: |
          curl -sSL https://install.tracer.cloud | CLI_BRANCH=dev sh -s ${{ secrets.TRACER_USER_ID }}
      - name: Run tracer init
        run: |
          sudo tracer init --token ${{ secrets.TRACER_TOKEN }} --pipeline-name github-actions

      - name: Run pipeline with Pixi
        working-directory: pipelines/macos-arm64/fastquorum
        run: |
          export NXF_GITHUB_TOKEN="${{ secrets.GITHUB_TOKEN }}"
          ./run.sh

      - name: Verify tracer packages
        uses: ./.github/actions/verify-tracer
        with:
          is_ebpf: false
          use_sudo: true
          binary: tracer
          required_processes_polling: "FastQC, fgbio FilterConsensusReads, samtools faidx, samtools dict, fgbio ZipperBams, samtools sort, bwa mem, bwa index, fgbio CallDuplexConsensusReads, fgbio GroupReadsByUmi, fgbio FastqToBam, fgbio CollectDuplexSeqMetrics"

      - name: Upload pipeline results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: fastquorum-arm64-pipeline-results
          path: |
            pipelines/macos-arm64/fastquorum/results/
            pipelines/macos-arm64/fastquorum/logs/
          retention-days: 7
