name: macOS intel pipelines

on:
  workflow_dispatch:
  push:
    paths:
      - "pipelines/macos-intel-x86/"
      - "pipelines/macos-intel-x86/"
      - ".github/workflows/macos-intel-x86.yml"
      - ".github/actions/verify-tracer/action.yml"
      - ".github/actions/install-tracer/action.yml"
  schedule:
    - cron: "*/2 * * * *"

jobs:
  fastquorum-pixi:
    name: Fastquorum macOS Intel x86
    runs-on: macos-13
    env:
      NXF_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4

      - name: Install tracer
        uses: ./.github/actions/install-tracer
        with:
          tracer_user_id: ${{ secrets.TRACER_USER_ID }}

      - name: Run tracer init
        run: |
          tracer init \
            --pipeline-name github-actions \
            --environment github-actions \
            --user-operator github-actions \
            --pipeline-type fastquorum \
            --dev

      - name: Run pipeline with Pixi
        working-directory: pipelines/macos-arm64/fastquorum
        run: |
          export NXF_GITHUB_TOKEN="${{ secrets.GITHUB_TOKEN }}"
          ./run.sh

      - name: Verify tracer packages
        uses: ./.github/actions/verify-tracer
        with:
          is_ebpf: false
          use_sudo: true
          binary: tracer
          # TODO: Add fgbio, multiqc to the list of processes
          required_processes_polling: "FastQC, samtools faidx, fgbio ZipperBams, bwa mem, bwa index, fgbio FastqToBam, samtools sort, fgbio CollectDuplexSeqMetrics, samtools dict, fgbio CallDuplexConsensusReads, fgbio GroupReadsByUmi"

      - name: Upload pipeline results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: fastquorum-arm64-pipeline-results
          path: |
            pipelines/macos-arm64/fastquorum/results/
            pipelines/macos-arm64/fastquorum/logs/
          retention-days: 7
