name: macOS intel pipelines

on:
  workflow_dispatch:

jobs:
  fastquorum-pixi:
    name: Fastquorum macOS Intel x86
    runs-on: macos-15-intel
    env:
      NXF_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      TRACER_USER_ID: ${{ secrets.TRACER_USER_ID }}
      TRACER_TOKEN: ${{ secrets.TRACER_TOKEN }}
    steps:
      - uses: actions/checkout@v4

      # - name: Install tracer
      #   uses: ./.github/actions/install-tracer
      #   with:
      #     tracer_user_id: ${{ secrets.TRACER_USER_ID }}
      - name: Install tracer
        run: |
          curl -sSL https://install.tracer.cloud | CLI_BRANCH=dev sh -s ${{ secrets.TRACER_USER_ID }}

      - name: Run tracer init
        run: |
          sudo tracer init --token ${{ secrets.TRACER_TOKEN }}

      - name: Run pipeline with Pixi
        working-directory: pipelines/macos-intel-x86/fastquorum
        run: |
          export NXF_GITHUB_TOKEN="${{ secrets.GITHUB_TOKEN }}"
          bash ./run.sh

      - name: Verify tracer packages
        uses: ./.github/actions/verify-tracer
        with:
          is_ebpf: false
          use_sudo: true
          binary: tracer
          # TODO: Add fgbio, multiqc to the list of processes
          required_processes_polling: "FastQC, samtools faidx, fgbio ZipperBams, bwa mem, bwa index, fgbio FastqToBam, samtools sort, fgbio CollectDuplexSeqMetrics, samtools dict, fgbio CallDuplexConsensusReads, fgbio GroupReadsByUmi"

      - name: Upload pipeline results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: fastquorum-intel-x86-pipeline-results
          path: |
            pipelines/macos-intel-x86/fastquorum/results/
            pipelines/macos-intel-x86/fastquorum/logs/
          retention-days: 7
