name: macOS intel pipelines

on:
  workflow_dispatch:
  push:
    paths:
      - "pipelines/macos-intel-x86/"
      - "pipelines/macos-intel-x86/"
      - ".github/workflows/macos-intel-x86.yml"
  schedule:
    - cron: "0 11 * * *"

jobs:
  fastquorum-pixi:
    name: Fastquorum macOS Intel x86
    runs-on: macos-13
    env:
      TRACER_BIO: /Users/runner/.tracerbio/bin/tracer
      NXF_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4

      - name: Install tracer
        continue-on-error: true
        run: |
          curl -sSL https://install.tracer.cloud | sh

      - name: Run tracer init
        run: |
          sudo $TRACER_BIO init --pipeline-name github-actions --environment github-actions --user-operator github-actions --pipeline-type nextflow --is-dev true

      - name: Run pipeline with Pixi
        working-directory: pipelines/macos-arm64/fastquorum
        run: |
          export NXF_GITHUB_TOKEN="${{ secrets.GITHUB_TOKEN }}"
          ./run.sh

      - name: Verify tracer packages
        uses: ./.github/actions/verify-tracer
        with:
          is_ebpf: false
          use_sudo: true
          binary: $TRACER_BIO
          required_processes_polling: "bwa,samtools sort,multiqc,fgbio GroupReadsByUmi,fgbio ZipperBams,fgbio FastqToBam,samtools dict,samtools faidx,fgbio CollectDuplexSeqMetrics,fgbio CallDuplexConsensusReads"

      - name: Upload pipeline results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: fastquorum-arm64-pipeline-results
          path: |
            pipelines/macos-arm64/fastquorum/results/
            pipelines/macos-arm64/fastquorum/logs/
          retention-days: 7
