name: Nextflow MacOS Intel x86 Pipelines

on:
  workflow_dispatch:
  push:
    paths:
      - "pipelines/macos-intel-x86/nextflow-pixi/**"
      - "pipelines/macos-intel-x86/nextflow-conda/**"
      - ".github/workflows/macos-intel-x86.yml"
  schedule:
    - cron: "0 11 * * *" # Daily at 11:00 UTC (12:00 BST)

jobs:
  macos-intel-x86-pixi:
    name: Pixi Pipeline
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v4

      - name: Install tracer
        continue-on-error: true
        run: |
          uses: ./.github/actions/tracer-client
          with:
            tracer_user_id: ${{ secrets.ACTIONS_TRACER_USER_ID }}

      - name: Run tracer init
        run: |
          sudo tracer init --pipeline-name github-actions --environment github-actions --user-operator github-actions --pipeline-type nextflow --is-dev true

      - name: Run pipeline with Pixi
        working-directory: pipelines/macos-intel-x86/nextflow-pixi
        run: |
          ./run.sh

      - name: Verify tracer packages
        uses: ./.github/actions/verify-tracer
        with:
          is_ebpf: false
          use_sudo: true
          binary: tracer

      - name: Upload pipeline results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: pixi-macos-intel-x86-pipeline-results
          path: |
            pipelines/macos-intel-x86/nextflow-pixi/results/
            pipelines/macos-intel-x86/nextflow-pixi/logs/
          retention-days: 7

  macos-intel-x86-conda:
    name: Conda Pipeline
    runs-on: macos-14

    steps:
      - uses: actions/checkout@v4

      - name: Install tracer
        continue-on-error: true
        uses: ./.github/actions/tracer-client
        with:
          tracer_user_id: ${{ secrets.ACTIONS_TRACER_USER_ID }}

      - name: Run tracer init
        run: |
          sudo tracer init --pipeline-name github-actions --environment github-actions --user-operator github-actions --pipeline-type nextflow --is-dev true

      - name: Run pipeline with Conda
        working-directory: pipelines/macos-intel-x86/nextflow-conda
        run: |
          ./run.sh

      - name: Verify tracer packages
        uses: ./.github/actions/verify-tracer
        with:
          is_ebpf: false
          use_sudo: true
          binary: tracer

      - name: Upload pipeline results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: conda-macos-intel-x86-pipeline-results
          path: |
            pipelines/macos-intel-x86/nextflow-conda/results/
            pipelines/macos-intel-x86/nextflow-conda/logs/
          retention-days: 7
