name: "Install Tracer Client"
author: "Vaibhav Upreti"
description: "Installs the Tracer Client"

branding:
  color: "blue"
  icon: "activity"

inputs:
  tracer_user_id:
    description: "Tracer User ID"
    required: false

runs:
  using: "composite"
  steps:
    - name: "Install Tracer Client"
      shell: bash
      run: |
        set -e

        # Install Tracer Client with or without user ID
        if [ -n "${{ inputs.tracer_user_id }}" ]; then
          export TRACER_USER_ID="${{ inputs.tracer_user_id }}"
        fi

        # Install Tracer as root (sudo), works for both Linux and macOS
        if [ "$(uname)" = "Darwin" ]; then
          bash -c "$(curl -fsSL https://install.tracer.cloud/)"
        else
          sudo bash -c "$(curl -fsSL https://install.tracer.cloud/)"
        fi

        # Add Tracer to PATH for all subsequent workflow steps
        if [ -d "$HOME/.tracerbio/bin" ]; then
          echo "$HOME/.tracerbio/bin" >> $GITHUB_PATH
        elif [ -d "/root/.tracerbio/bin" ]; then
          echo "/root/.tracerbio/bin" >> $GITHUB_PATH
        fi

        export PATH="$HOME/.tracerbio/bin:/root/.tracerbio/bin:$PATH"

    - name: "Verify Tracer Client"
      shell: bash
      run: |
        tracer info
