name: "Install Tracer Client"
author: "Vaibhav Upreti"
description: "Installs Tracer Client"

branding:
  color: "blue"
  icon: "activity"

inputs:
  tracer_user_id:
    description: "Tracer User ID"
    required: false

runs:
  using: "composite"
  steps:
    - name: "Install Tracer Client"
      shell: bash
      run: |
        set -e
        if [ -n "${{ inputs.tracer_user_id }}" ]; then
          export TRACER_USER_ID="${{ inputs.tracer_user_id }}"
        fi

        curl -sSL https://install.tracer.cloud | sh

        if [ -n "$BASH_VERSION" ] && [ -f "$HOME/.bashrc" ]; then
          source "$HOME/.bashrc"
        elif [ -n "$ZSH_VERSION" ] && [ -f "$HOME/.zshrc" ]; then
          source "$HOME/.zshrc"
        elif [ -f "$HOME/.profile" ]; then
          source "$HOME/.profile"
        fi

        echo "PATH after patch: $PATH"
        tracer --version || true

    - name: "Verify Tracer Installation"
      shell: bash
      run: |
        tracer --version
