name: "Install Tracer Client"
author: "Vaibhav Upreti"
description: "Installs the Tracer Client"

branding:
  color: "blue"
  icon: "activity"

inputs:
  tracer_user_id:
    description: "Tracer User ID"
    required: false

runs:
  using: "composite"
  steps:
    - name: "Install Tracer Client"
      shell: bash
      run: |
        set -e

        # Always resolve HOME to the current user's home directory
        USER_HOME=$(eval echo ~$USER)
        TRACER_BIN="$USER_HOME/.tracerbio/bin/tracer"
        TRACER_DIR="$USER_HOME/.tracerbio/bin"

        # Install Tracer Client with or without user ID
        if [ -n "${{ inputs.tracer_user_id }}" ]; then
          export TRACER_USER_ID="${{ inputs.tracer_user_id }}"
        fi

        # Install Tracer as root (sudo), works for both Linux and macOS
        if [ "$(uname)" = "Darwin" ]; then
          bash -c "$(curl -fsSL https://install.tracer.cloud/)"
        else
          sudo bash -c "$(curl -fsSL https://install.tracer.cloud/)"
        fi

        # Ensure $USER_HOME/.tracerbio/bin exists and contains the tracer binary
        mkdir -p "$TRACER_DIR"
        if [ -f "/root/.tracerbio/bin/tracer" ] && [ ! -f "$TRACER_BIN" ]; then
          cp /root/.tracerbio/bin/tracer "$TRACER_BIN"
        fi

        # Add Tracer to PATH for all subsequent workflow steps
        echo "$TRACER_DIR" >> $GITHUB_PATH
        export PATH="$TRACER_DIR:$PATH"

        # Print debug info
        echo "PATH after install: $PATH"
        which tracer || true
        ls -l "$TRACER_BIN" || true
        tracer --version || true

    - name: "Verify Tracer Client"
      shell: bash
      run: |
        tracer info
