name: "Install Tracer Client"
author: "Vaibhav Upreti"
description: "Installs the Tracer Client"

branding:
  color: "blue"
  icon: "activity"

inputs:
  tracer_user_id:
    description: "Tracer User ID"
    required: false

runs:
  using: "composite"
  steps:
    - name: "Install Tracer Client"
      shell: bash
      run: |
        set -e

        # Install Tracer Client with or without user ID
        if [ -n "${{ inputs.tracer_user_id }}" ]; then
          export TRACER_USER_ID="${{ inputs.tracer_user_id }}"
        fi

        if [ "$(uname)" = "Darwin" ]; then
          # macOS: install to $HOME
          bash -c "$(curl -fsSL https://install.tracer.cloud/)"
          TRACER_BIN="$HOME/.tracerbio/bin/tracer"
          TRACER_DIR="$HOME/.tracerbio/bin"
        else
          # Linux: install to /root, copy to /home/runner
          sudo bash -c "$(curl -fsSL https://install.tracer.cloud/)"
          mkdir -p /home/runner/.tracerbio/bin
          if [ -f /root/.tracerbio/bin/tracer ]; then
            cp /root/.tracerbio/bin/tracer /home/runner/.tracerbio/bin/tracer
          fi
          TRACER_BIN="/home/runner/.tracerbio/bin/tracer"
          TRACER_DIR="/home/runner/.tracerbio/bin"
        fi

        # Add Tracer to PATH for all subsequent workflow steps
        echo "$TRACER_DIR" >> $GITHUB_PATH
        export PATH="$TRACER_DIR:$PATH"

        # Print debug info
        echo "PATH after install: $PATH"
        which tracer || true
        ls -l "$TRACER_BIN" || true
        tracer --version || true

    - name: "Verify Tracer Client"
      shell: bash
      run: |
        tracer info
