name: "Install Tracer Client"
author: "Vaibhav Upreti"
description: "Installs the Tracer Client"

branding:
  color: "blue"
  icon: "activity"

inputs:
  tracer_user_id:
    description: "Tracer User ID"
    required: false

runs:
  using: "composite"
  steps:
    - name: "Install Tracer Client"
      shell: bash
      run: |
        set -e
        # Install Tracer Client with or without user ID
        if [ -n "${{ inputs.tracer_user_id }}" ]; then
          export TRACER_USER_ID="${{ inputs.tracer_user_id }}"
        fi
        curl -sSL https://install.tracer.cloud/ | sudo bash
        # Add Tracer to PATH for all subsequent workflow steps
        echo "/root/.tracerbio/bin" >> $GITHUB_PATH
        export PATH="/root/.tracerbio/bin:$PATH"
        # Print debug info
        echo "PATH after install: $PATH"
        which tracer || true
        sudo ls -l "/root/.tracerbio/bin/tracer" || true
        tracer --version || true
    - name: "Verify Tracer Client"
      shell: bash
      run: |
        tracer info
