name: rnaseq-minimal
channels:
  - conda-forge
  - bioconda
  - defaults

dependencies:
  # Core tools only - minimal installation
  - nextflow>=24.10.0
  - openjdk=17
  
  # Essential RNA-seq tools only
  - fastqc=0.12.1
  - samtools=1.21
  
  # System utilities
  - gawk
  - coreutils
  - bc
